services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: UTNExamen
      MYSQL_USER: examen_user
      MYSQL_PASSWORD: examen_pass
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  api:
    build: 
      context: .
      target: dev
    container_name: api_service
    restart: on-failure
    depends_on:
      - mysql_db
    environment:
      NODE-ENV: development
      PORT: 3000
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USER: examen_user
      DB_PASSWORD: examen_pass
      DB_NAME: UTNExamen
      JWT_SECRET: secreto_examen
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  adminer:
    image: adminer
    container_name: adminer_examen
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: