services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: UTNExamen
      MYSQL_USER: examen_user
      MYSQL_PASSWORD: examen_pass
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  adminer:
    image: adminer
    container_name: adminer_examen
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: